# Generated by Django 4.2.3 on 2023-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loadingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plat',
            name='vegetarien',
            field=models.BooleanField(default=False),
        ),
    ]
